[WIP] - Slash commands
kordlib/kord pull request #145
Opened 2020-12-18 18:35 UTC by HopeBaron

# What this PR should Implement
[X] Gateways related to slash commands.
[X] REST endpoints
[] Core representations

# Issues encountered

> Slash Commands and Interactions bring something entirely new to the table: the ability to interact with an application without needing a bot user in the guild. As you read through this documentation, you'll see that bot tokens are only referenced as a helpful alternative to doing a client credentials auth flow. Slash Commands do not depend on a bot user in the guild; responding to interactions does not require a bot token.

As the [Discord docs](https://discord.com/developers/docs/interactions/slash-commands#slash-commands-interactions-and-bot-users) states , neither a slash command doesn't depend on a bot user, nor a bot user requires a slash commands to work.
# Solutions proposed

One simple solution to the problem, is to allow `applicationId` be nullable as follows:
```kotlin
    suspend fun createGlobalApplicationCommand(
        name: String,
        description: String,
        builder: GlobalApplicationCommandCreateBuilder.() -> Unit
    ) {
        if(resources.applicationId == null) throw IllegalArgumentException("applicationId must not be null")
        val request = GlobalApplicationCommandCreateBuilder(name, description).apply(builder).toRequest()
        rest.interaction.createGlobalApplicationCommand(applicationId, request)
    }
```
    
But this wouldn't provide the user with a useful message or warning if the `applicationId` was null. In addition, this would require to validate `applicationId` each time we work with it.

---

Provide an annotation warning the same way we did for intents. 
However annotations can be ignored and do not provide a strict message as well.
---

Move interactions into their own class that works along side Kord `e.g: SlashCommands`

This is the best solution we have at the moment. 
The problem is that this solution limts Kord's control over slash commands overall.
```kotlin
val commands: SlashCommands = Kord.toSlashCommand(appId: String)
```
if we were going to use this object to create a command from message, or any other context we will need to keep a reference and limits the flexibility of code writing.

2020-12-19 16:17 UTC, HopeBaron commented
The team agreed on the following solution:

* A rest-only entity which is responsible for application commands created (currently named `SlashCommands`)
This would allow creating, editing, or deleting slash command's related records without a gateway.

* Kord will allow a nullable `appId`

* Two versions of `Interaction` events will be created. 

`Interaction` - offers data from the `INTERACTION_CREATE` event with no functionality (`Kord `will use this if `appId` is null)
`InteractionBehavior` - offers data, with functionality, and derives from `Interaction`

# How does this solve the problem

Kord will introduce a event handler for the interaction create event, which keeps track of the nullity of the appId. In-case the appId was null, the event handler won't emit an `InteractionBehavior` object a filtered flow for that event will always be empty. Otherwise, the user  will be able to pick both events from the event flow.

Below are some code samples 

```kt
val kord = Kord(bot_id) { appid = null }
kord.on<InteractionBehavior> {  // flow will always be empty since `appId` is null

}
```


```kt
val kord = Kord(bot_id) { appid = null }
kord.on<Interaction> {  // flow emits even if appId is null

}
```

```kt
val kord = Kord(bot_id) { appid = appId }
kord.on<InteractionBehavior> {  // flow emits since appId is not null

}
```

2020-12-26 10:43 UTC, BartArys requested changes
Looks good for the most part, missed quite a few @KordPreview in the gateway module though.

2020-12-26 10:43 UTC, BartArys commented on common/src/main/kotlin/entity/Interactions.kt
> +    val choices: Optional<List<Choice<@Serializable(NotSerializable::class) Any?>>> = Optional.Missing(),
Might want to clarify in the code why this is needed

2020-12-26 10:43 UTC, BartArys commented on common/src/main/kotlin/entity/Interactions.kt
> +}
Give some better errors here, and perhaps document what this is for.

2020-12-26 10:43 UTC, BartArys commented on common/src/main/kotlin/entity/Interactions.kt
> +    object Unknown : ApplicationCommandOptionType(Int.MAX_VALUE)
make this a class, and have it accept the type as an argument

2020-12-26 10:43 UTC, BartArys commented on common/src/main/kotlin/entity/Interactions.kt
> +    object Serializer : KSerializer<ApplicationCommandOptionType> {
Make this internal

2020-12-26 10:43 UTC, BartArys commented on common/src/main/kotlin/entity/Interactions.kt
> +    internal class ChoiceSerializer<T>(serializer: KSerializer<T>) : KSerializer<Choice<*>> {
Document why this serializer is ignored.

2020-12-26 10:43 UTC, BartArys commented on common/src/main/kotlin/entity/Interactions.kt
> +            return if(value.isString) StringChoice(name, value.toString()) else IntChoice(name, value.int)
I think it'd be better if we gave a proper error when the type isn't string nor int. This shouldn't happen (yet?), but it'll probably save us some work when they eventually break this stuff.

2020-12-26 10:43 UTC, BartArys commented on common/src/main/kotlin/entity/Interactions.kt
> +    object Serializer : KSerializer<InteractionType> {
make this internal.

2020-12-26 10:43 UTC, BartArys commented on common/src/main/kotlin/entity/Interactions.kt
> +    object Serializer : KSerializer<InteractionResponseType> {
Make this internal

2020-12-26 10:43 UTC, BartArys commented on common/src/main/kotlin/entity/Interactions.kt
> +    object Unknown : InteractionResponseType(Int.MAX_VALUE)
Make this a class, and have it accept the type as an argument

2020-12-26 10:43 UTC, BartArys commented on core/src/main/kotlin/SlashCommands.kt
> +    }
all of these should be inline, all DSL objects should be marked with the builder annotation

2020-12-26 10:43 UTC, BartArys commented on core/src/main/kotlin/behavior/InteractionBehavior.kt
> +    }
Needs to be inline

2020-12-26 10:43 UTC, BartArys commented on core/src/main/kotlin/behavior/InteractionBehavior.kt
> +    }
Needs to be inline.

2020-12-26 10:43 UTC, BartArys commented on core/src/main/kotlin/entity/interaction/Interaction.kt
> +}
Needs getEntity(OrNull) variants for the guildId and channelId. + Strategizable.

2020-12-26 10:43 UTC, BartArys commented on core/src/main/kotlin/entity/interaction/Interaction.kt
> +}
Needs getEntity(OrNull) variants for the guildId and channelId. + Strategizable.

2020-12-26 10:43 UTC, BartArys commented on core/src/main/kotlin/entity/interaction/Interaction.kt
> +}
Try and see if we can split this off to groups/subcommands and options/parameters.

2020-12-26 10:43 UTC, BartArys commented on core/src/main/kotlin/gateway/handler/InteractionEventHandler.kt
> +        }
This will result in the same event getting sent twice if app id is present. Consider only the most relevant one instead.

2020-12-26 10:43 UTC, BartArys commented on core/src/test/kotlin/regression/CacheMissRegression.kt
> -object FakeGateway : Gateway {
Why did this get deleted?

2020-12-26 10:43 UTC, BartArys commented on rest/src/main/kotlin/route/Route.kt
> +    object InteractionToken : Key("{interaction.token}")
I don't think it's documented anywhere, but are any of these 'major' keys? I assume they are.

2021-01-03 12:36 UTC, BartArys requested changes

2021-01-03 12:36 UTC, BartArys commented on core/src/main/kotlin/SlashCommands.kt
> +    @ExperimentalContracts
OptIn instead

2021-01-03 12:36 UTC, BartArys commented on core/src/main/kotlin/SlashCommands.kt
> +    @ExperimentalContracts
OptIn instead

2021-01-03 12:36 UTC, BartArys commented on core/src/main/kotlin/behavior/FollowupMessageBehavior.kt
> +@ExperimentalContracts
OptIn instead

2021-01-03 12:36 UTC, BartArys commented on core/src/main/kotlin/behavior/InteractionBehavior.kt
> +     * An acknowledgement that have no message attached to it.
`@returns`

2021-01-03 12:36 UTC, BartArys commented on core/src/main/kotlin/behavior/InteractionBehavior.kt
> +     * [source] weather to show the source (author's name and provided arguments of the command).
`@args`

2021-01-03 12:36 UTC, BartArys commented on core/src/main/kotlin/behavior/InteractionBehavior.kt
> +     * Returns an [InteractionResponseBehavior] which can be used to create follow-up message or edit the original response
`@returns`

2021-01-03 12:36 UTC, BartArys commented on core/src/main/kotlin/behavior/InteractionBehavior.kt
> + * An acknowledgement that have a message attached to it built using [builder] with an initial [content] value.
`@returns`

2021-01-03 12:36 UTC, BartArys commented on core/src/main/kotlin/behavior/InteractionBehavior.kt
> + * [source] weather to show the source (author's name and provided arguments of the command).
`@args`

2021-01-03 12:36 UTC, BartArys commented on core/src/main/kotlin/behavior/InteractionBehavior.kt
> + * Returns an [InteractionResponseBehavior] which can be used to create follow-up message or edit the original response
`@returns`

2021-01-03 12:36 UTC, BartArys commented on core/src/main/kotlin/behavior/InteractionBehavior.kt
> +@ExperimentalContracts
OptIn instead

2021-01-03 12:36 UTC, BartArys commented on core/src/main/kotlin/behavior/InteractionBehavior.kt
> + * An acknowledgement that have no message attached to it.
`@returns`

2021-01-03 12:36 UTC, BartArys commented on core/src/main/kotlin/behavior/InteractionBehavior.kt
> + * [source] weather to show the source (author's name and provided arguments of the command).
`@args`

2021-01-03 12:36 UTC, BartArys commented on core/src/main/kotlin/behavior/InteractionResponseBehavior.kt
> +@ExperimentalContracts
OptIn instead

2021-01-03 12:36 UTC, BartArys commented on core/src/main/kotlin/behavior/InteractionResponseBehavior.kt
> +@ExperimentalContracts
OptIn instead

2021-01-03 12:36 UTC, BartArys commented on core/src/main/kotlin/cache/data/InteractionData.kt
> + * A serializer that's sole purpose is to provide a No-Op serializer for [Any].
whose sole purpose*

2021-01-03 12:36 UTC, BartArys commented on core/src/main/kotlin/cache/data/InteractionData.kt
> + * Since kotlinx.serialization doesn't allow using [Any] in a generic context.
Should clarify that this is for scenarios where the serialization type is not know and not relevant to the serialization itself.

2021-01-03 12:36 UTC, BartArys commented on core/src/main/kotlin/entity/interaction/Interaction.kt
> +    val subCommands: Map<String, SubCommand>
Should clarify that these are the direct subcommands, not including those in `groups`.

2021-01-03 12:36 UTC, BartArys commented on rest/src/main/kotlin/builder/interaction/InteractionsBuilder.kt
> +    @ExperimentalContracts
OptIn instead

2021-01-03 12:36 UTC, BartArys commented on rest/src/main/kotlin/builder/interaction/InteractionsBuilder.kt
> +    @ExperimentalContracts
OptIn instead

2021-01-03 12:36 UTC, BartArys commented on rest/src/main/kotlin/builder/interaction/InteractionsBuilder.kt
> +    @ExperimentalContracts
OptIn instead

2021-01-03 12:36 UTC, BartArys commented on rest/src/main/kotlin/builder/interaction/InteractionsBuilder.kt
> +    @ExperimentalContracts
OptIn instead

2021-01-03 12:36 UTC, BartArys commented on rest/src/main/kotlin/builder/interaction/InteractionsBuilder.kt
> +    @ExperimentalContracts
OptIn instead

2021-01-03 12:36 UTC, BartArys commented on rest/src/main/kotlin/builder/interaction/InteractionsBuilder.kt
> +    @ExperimentalContracts
OptIn instead

2021-01-03 12:36 UTC, BartArys commented on rest/src/main/kotlin/builder/interaction/InteractionsBuilder.kt
> +    @ExperimentalContracts
OptIn instead

2021-01-03 12:36 UTC, BartArys commented on rest/src/main/kotlin/builder/interaction/InteractionsBuilder.kt
> +    @ExperimentalContracts
OptIn instead

2021-01-03 12:36 UTC, BartArys commented on rest/src/main/kotlin/builder/interaction/OptionsBuilder.kt
> +    @ExperimentalContracts
OptIn instead

2021-01-03 12:36 UTC, BartArys commented on rest/src/main/kotlin/builder/interaction/OptionsBuilder.kt
> +    @ExperimentalContracts
OptIn instead

2021-01-03 12:36 UTC, BartArys commented on rest/src/main/kotlin/builder/interaction/OptionsBuilder.kt
> +    @ExperimentalContracts
OptIn instead

2021-01-03 12:36 UTC, BartArys commented on rest/src/main/kotlin/builder/interaction/OptionsBuilder.kt
> +    @ExperimentalContracts
OptIn instead

2021-01-03 12:36 UTC, BartArys commented on rest/src/main/kotlin/builder/interaction/OptionsBuilder.kt
> +    @ExperimentalContracts
OptIn instead

2021-01-03 12:36 UTC, BartArys commented on rest/src/main/kotlin/builder/interaction/OptionsBuilder.kt
> +    @ExperimentalContracts
OptIn instead

2021-01-03 15:38 UTC, BartArys approved these changes

2021-01-04 19:50 UTC, BartArys approved these changes

2021-01-04 22:49 UTC, BartArys approved these changes

2021-01-05 10:18 UTC, merged