Add membership screening
kordlib/kord pull request #218
Opened 2021-03-25 19:58 UTC by DRSchlaubi

- Adds discord/discord-api-docs#2396
- Add models
- Add rest requests

Related to #121, #216

2021-04-05 10:57 UTC, HopeBaron requested changes
There is no core representation for member screening

2021-04-05 10:57 UTC, HopeBaron commented on common/src/main/kotlin/entity/DiscordGuild.kt
> +        enum class Type {
Use a more expresive name than `Type`, maybe `FormFieldType` is a better. name
Also use objects so we can have `Unknown` type in there

2021-04-05 12:14 UTC, DRSchlaubi commented
actually, they removed the docs for membership screening so I stopped implementing them until they do a PR adding them again

2021-04-18 14:02 UTC, HopeBaron commented
Any updates on this?

2021-04-18 14:05 UTC, DRSchlaubi commented
https://discord.com/developers/docs/resources/guild#membership-screening-object still has the warning and I don't see any PR changeing it so I guess no updates

2021-04-18 14:06 UTC, HopeBaron commented
Understood :+1:

2023-02-16 11:53 UTC, closed without merging