Implement slash command permissions
kordlib/kord pull request #224
Opened 2021-03-27 17:10 UTC by DRSchlaubi

This implements discord/discord-api-docs#2737
I will update this PR in case the Discord PR get's updated

2021-04-09 19:39 UTC, DRSchlaubi commented
Welp i totally missed that they merged it

2021-04-13 16:56 UTC, BartArys commented
Your commit contains over 300 purely cosmetic changes (some in otherwise untouched files). Could you please on PR changes that are relevant to the PR? I don't have the mental capacity to go over all these changes in detail and I might end up missing stuff like this: 
![image](https://user-images.githubusercontent.com/18498008/114591121-d7ce3480-9c89-11eb-9bd8-5474ff8057f3.png)

2021-04-13 17:25 UTC, DRSchlaubi commented
> Your commit contains over 300 purely cosmetic changes (some in otherwise untouched files). Could you please on PR changes that are relevant to the PR? I don't have the mental capacity to go over all these changes in detail and I might end up missing stuff like this:
> ![image](https://user-images.githubusercontent.com/18498008/114591121-d7ce3480-9c89-11eb-9bd8-5474ff8057f3.png)

Thats why we need #186 because If I format my file it formats everything else as well. Also I might screwed up something whilst switching branches and inherited some changes that i didn't want to put in here

2021-04-15 10:18 UTC, HopeBaron commented
You should be using Kord's standard formatting until we merge the styling branch. which would preferably be after everything important has been merged

2021-04-15 12:36 UTC, HopeBaron requested changes

2021-04-15 12:36 UTC, HopeBaron commented on common/src/main/kotlin/entity/Interactions.kt
> +
I'd say a class with `object`s would be more useful than an enum in case Discord, somewhat introduced a new type of permissions

2021-04-15 12:55 UTC, DRSchlaubi commented
> You should be using Kord's standard formatting until we merge the styling branch. which would preferably be after everything important has been merged

That's why I made that PR what even is the Style Kord uses

2021-04-15 13:54 UTC, DRSchlaubi commented
Superseeded by #253

2021-04-15 13:54 UTC, closed without merging