Sealed message types
kordlib/kord pull request #282
Opened 2021-05-12 18:56 UTC by HopeBaron

2021-05-12 19:01 UTC, BartArys commented
Consider adding the new message types as well https://discord.com/developers/docs/resources/channel#message-object-message-types

2021-05-12 19:19 UTC, HopeBaron commented
Done.

2021-05-12 19:43 UTC, BartArys requested changes

2021-05-12 19:43 UTC, BartArys commented on common/src/main/kotlin/entity/DiscordMessage.kt
> +    object MessageTypeSerializer : KSerializer<MessageType> {
While we're at it, make this internal, users have no need for it

```suggestion
    internal object MessageTypeSerializer : KSerializer<MessageType> {
```

2021-05-13 08:43 UTC, BartArys approved these changes

2021-05-14 07:29 UTC, merged