Add AutoComplete
kordlib/kord pull request #435
Opened 2021-10-28 16:26 UTC by DRSchlaubi

<https://github.com/discord/discord-api-docs/pull/3996>

- Add support for AutoComplete options
- Update Core representation

2021-11-10 04:21 UTC, HopeBaron requested changes

2021-11-10 04:21 UTC, HopeBaron commented on rest/src/main/kotlin/builder/interaction/OptionsBuilder.kt
> +     * Core users can check the `AutoCompleteInteractionCreateEvent` and `AutoCompleteInteraction` classes.
use mark down to link to the mentioned classes

2021-11-10 12:57 UTC, DRSchlaubi commented
@HopeBaron Those classes are in the core module, the file above is rest, so these links don't work
No idea why but couldn't reply to your convo above directly

2021-11-10 16:04 UTC, HopeBaron commented
There is no need for such documentation when you can't refer to it. rest module is unaware of events.

This sort of documentation may become invalid since refactoring may now work on those so they will become lies if things change. And Kord has already enough of those kinds of documentation that we should be working on already. 
Remove them for now also I'd like you to integrate warnings and Notes without bold headers.

2021-11-18 11:43 UTC, HopeBaron commented
why "MessageResponding"
I guess you mixed it up with `InteractionResponse`?

2021-11-18 13:17 UTC, DRSchlaubi commented
Because these interactions respond with a Message unlike AutoComplete which respond with a Choices object.

I think it was @BartArys who suggested MessageResponding

2021-11-19 08:38 UTC, HopeBaron commented
not all commands should respond with a message. it may be a command with no message, and chatinput now implements only `Interaction` instead of `ApplicationCommandInteraction`
I don't get why this happened...

They are all application commands, it's just that AutoComplete responds diferently, right?

2021-11-19 19:32 UTC, DRSchlaubi commented
> and chatinput now implements only Interaction instead of ApplicationCommandInteraction
I don't get why this happened...

Okay that was unintended

> They are all application commands, it's just that AutoComplete responds diferently, right?

yes this is why MessageRespondingInteraction is everything but autocomplete, but I am open for better names

2021-11-25 05:53 UTC, merged