Add support for attachment options in chat input interactions
kordlib/kord pull request #524
Opened 2022-02-06 16:23 UTC by MrPowerGamerBR

2022-02-06 18:10 UTC, MrPowerGamerBR commented
**`InteractionCreate` event when a attachment is sent:**
```
InteractionCreate(interaction=DiscordInteraction(id=939946131327176734, applicationId=936390863704178758, type=InteractionType.ApplicationCommand(2), data=InteractionCallbackData(id=OptionalSnowflake.Value(snowflake=939920456784416808), type=Optional.Something(content=dev.kord.common.entity.ApplicationCommandType$ChatInput@301fd2df), targetId=OptionalSnowflake.Missing, name=Optional.Something(content=attachmenttest), resolved=Optional.Something(content=ResolvedObjects(members=Optional.Missing, users=Optional.Missing, roles=Optional.Missing, channels=Optional.Missing, messages=Optional.Missing, attachments=Optional.Something(content={939946130303762452=DiscordAttachment(id=939946130303762452, filename=859686182404882452.png, description=Optional.Missing, contentType=Optional.Something(content=image/png), size=40433, url=https://cdn.discordapp.com/ephemeral-attachments/939920456784416808/939946130303762452/859686182404882452.png, proxyUrl=https://media.discordapp.net/ephemeral-attachments/939920456784416808/939946130303762452/859686182404882452.png, height=Optional.Value(value=248), width=Optional.Value(value=252), ephemeral=Optional.Value(value=true))}))), options=Optional.Something(content=[UserArgument(name=attachment, value=939946130303762452, focused=OptionalBoolean.Missing)]), customId=Optional.Missing, componentType=Optional.Missing, values=Optional.Missing), guildId=OptionalSnowflake.Value(snowflake=936391274951503873), channelId=936391275391897652, member=Optional.Something(content=DiscordInteractionGuildMember(user=Optional.Something(content=DiscordUser(id=123170274651668480, username=MrPowerGamerBR, discriminator=4185, avatar=8bd2b747f135c65fd2da873c34ba485c, bot=OptionalBoolean.Missing, system=OptionalBoolean.Missing, mfaEnabled=OptionalBoolean.Missing, locale=Optional.Missing, verified=OptionalBoolean.Missing, email=Optional.Missing, flags=Optional.Missing, premiumType=Optional.Missing, publicFlags=Optional.Something(content=UserFlags(code=131712)), banner=null, accentColor=null)), nick=Optional.Null, roles=[], joinedAt=2022-01-27T22:44:37.270000+00:00, premiumSince=Optional.Null, permissions=Permissions(values=DiscordBitSet(11111111111111111111111111111111111111111)), pending=Optional.Value(value=false), avatar=Optional.Null, communicationDisabledUntil=Optional.Null)), user=Optional.Missing, token=no_u, version=1, message=Optional.Missing, locale=Optional.Something(content=Locale(language=en, country=GB)), guildLocale=Optional.Something(content=Locale(language=en, country=US))), sequence=3)
```

2022-02-09 01:59 UTC, Lukellmann requested changes

2022-02-09 01:59 UTC, Lukellmann commented on common/src/main/kotlin/entity/Interactions.kt
> +                ApplicationCommandOptionType.Attachment -> UserArgument(
```suggestion
                ApplicationCommandOptionType.Attachment -> AttachmentArgument(
```

2022-02-09 02:03 UTC, MrPowerGamerBR commented on common/src/main/kotlin/entity/Interactions.kt
> +                ApplicationCommandOptionType.Attachment -> UserArgument(
whoops

2022-02-09 02:04 UTC, Lukellmann approved these changes

2022-02-11 03:47 UTC, merged