Voice text
kordlib/kord pull request #614
Opened 2022-06-05 05:48 UTC by HopeBaron

2022-06-05 21:29 UTC, Lukellmann requested changes

2022-06-05 21:29 UTC, Lukellmann commented on core/src/main/kotlin/entity/channel/VoiceChannel.kt
> +) : CategorizableChannel, TopGuildMessageChannel, VoiceChannelBehavior {
```suggestion
) : TopGuildMessageChannel, VoiceChannelBehavior {
```
`TopGuildMessageChannel` is already a `CategorizableChannel`

2022-06-05 21:29 UTC, Lukellmann commented on core/src/main/kotlin/entity/channel/VoiceChannel.kt
> +    override suspend fun fetchChannel(): VoiceChannel = supplier.getChannelOf(id)
Why do we need these overrides?

2022-06-07 06:03 UTC, HopeBaron commented on core/src/main/kotlin/entity/channel/VoiceChannel.kt
> +    override suspend fun fetchChannel(): VoiceChannel = supplier.getChannelOf(id)
to return a voice type channel

2022-06-10 18:16 UTC, Lukellmann approved these changes

2022-06-10 18:49 UTC, NoComment1105 approved these changes

2022-06-10 19:41 UTC, merged