Fix nonce deserialization (Alternative Solution)
kordlib/kord pull request #632
Opened 2022-06-27 11:53 UTC by MrPowerGamerBR

![image](https://user-images.githubusercontent.com/9496359/175935185-fb5dcbc2-9b04-4f6d-966a-17157f725ee5.png)

Fixes #629

2022-06-27 15:35 UTC, Lukellmann requested changes
I would also go for this solution, this doesn't introduce yet another type.

2022-06-27 15:35 UTC, Lukellmann commented on common/src/main/kotlin/entity/DiscordMessage.kt
> +internal object NonceAsStringSerializer : KSerializer<String> {
I've implemented something similar [here](https://github.com/kordlib/kord/blob/0.8.x/common/src/main/kotlin/entity/AuditLog.kt#L319). I suggest a refactor to use the same serializer in both places.
A good place to put this serializer would be [here](https://github.com/kordlib/kord/tree/0.8.x/common/src/main/kotlin/serialization).

2022-06-28 12:24 UTC, Lukellmann reviewed
looks good overall, just some minor suggestions

2022-06-28 12:24 UTC, Lukellmann commented on common/src/main/kotlin/entity/AuditLog.kt
>      }
```suggestion
```
the block is no longer needed

2022-06-28 12:24 UTC, Lukellmann commented on common/src/main/kotlin/entity/DiscordMessage.kt
> +import kotlinx.serialization.json.jsonPrimitive
```suggestion
```
we no longer need these imports

2022-06-28 14:14 UTC, MrPowerGamerBR commented
For some reason the "Add suggestion to batch" was grayed out, that's why I needed to apply all suggestions one by one 😭

2022-06-28 14:16 UTC, Lukellmann commented
> For some reason the "Add suggestion to batch" was grayed out, that's why I needed to apply all suggestions one by one 😭

iirc applying batch suggestions is only available in the "Files changed" tab

2022-07-02 09:15 UTC, merged