Simplify CI
kordlib/kord pull request #823
Opened 2023-04-27 23:36 UTC by Lukellmann

* call Git CLI from Gradle instead of depending on CI specifics
* use normal environment variables for signing
* remove JitPack support, we publish snapshots for all branches anyway

2023-04-27 23:37 UTC, Lukellmann commented
#822 should be based on this

2023-04-28 07:27 UTC, NoComment1105 approved these changes

2023-04-29 21:40 UTC, DRSchlaubi requested changes

2023-04-29 21:40 UTC, DRSchlaubi commented on .github/workflows/docs-ci.yml
>        GITHUB_TAG_NAME: ${{ github.event.release.tag_name }}
Should we replace this too?

2023-04-30 19:25 UTC, Lukellmann commented on .github/workflows/docs-ci.yml
>        GITHUB_TAG_NAME: ${{ github.event.release.tag_name }}
sure

2023-04-30 21:19 UTC, DRSchlaubi approved these changes

2023-04-30 21:24 UTC, merged