Migrated Snowflake to inline class
kordlib/kord pull request #886
Opened 2023-10-24 00:42 UTC by zTrap

Mockk does not yet supported good boxing\unboxing for inline classes. So most tests are broken

2023-10-24 08:33 UTC, lukellmann reviewed
can you run `./gradlew apiDump` and commit the result? i want to know how bad it's going to be...

2023-10-24 08:33 UTC, lukellmann commented on common/src/commonMain/kotlin/entity/Snowflake.kt
> -     */
i think this documentation should be kept

2023-10-24 08:33 UTC, lukellmann commented on common/src/commonMain/kotlin/entity/optional/OptionalSnowflake.kt
> +            Value(Snowflake(decoder.decodeInline(descriptor).decodeLong().toULong()))
can be delegated to `Snowflake`'s serializer instead

2023-10-24 16:19 UTC, lukellmann commented
Is there an issue already for the problems with mockk?

2023-10-24 16:45 UTC, zTrap commented
I've got wrong. This problem isn't related to inline classes, but to unsigned numbers. https://github.com/mockk/mockk/issues/544

2024-01-31 21:20 UTC, lukellmann commented
> I've got wrong. This problem isn't related to inline classes, but to unsigned numbers. [mockk/mockk#544](https://github.com/mockk/mockk/issues/544)

the issue you pointed to is now closed, is there any update on this?

2024-02-01 00:43 UTC, zTrap commented
Yes, issue is closed, but it not released yet

2024-05-29 12:06 UTC, zTrap commented
@lukellmann seems like all works fine with `mockk` v1.13.11

2024-05-30 16:21 UTC, lukellmann commented
I'd like to discuss this some more before deciding what to do with this, see https://discord.com/channels/556525343595298817/1245773750486438060

2024-06-04 09:37 UTC, lukellmann commented
i've updated the target branch btw

2024-06-04 09:38 UTC, lukellmann requested changes

2024-06-05 07:11 UTC, lukellmann approved these changes

2024-06-05 07:15 UTC, merged

2024-06-05 07:18 UTC, lukellmann commented
these changes can be tested using `experiments-inline-value-classes-SNAPSHOT`