Add support for application emojis
kordlib/kord pull request #973
Opened 2024-08-25 15:07 UTC by DRSchlaubi

2025-04-23 21:06 UTC, psmarko requested changes
Few little things need fixing like route keys and Discord not supporting audit log reasons.

2025-04-23 21:06 UTC, psmarko commented on rest/src/commonMain/kotlin/service/ApplicationService.kt
> +        reason: String? = null,
Application emojis don't support the audit log header.

```suggestion
```

2025-04-24 00:29 UTC, DRSchlaubi commented on rest/src/commonMain/kotlin/service/ApplicationService.kt
> +    public suspend fun createApplicationEmoji(appId: Snowflake, request: EmojiCreateRequest): DiscordEmoji =
I think breaking the API for this is not worth it, so let's just leave this as is

2025-04-26 16:02 UTC, merged

2025-04-26 16:53 UTC, lukellmann requested changes
Sorry for the late review after merge, can you address my comments in a followup PR @DRSchlaubi?

2025-04-26 16:53 UTC, lukellmann commented on common/src/commonMain/kotlin/entity/DiscordEmoji.kt
> +public data class ApplicationEmojis(val items: List<DiscordEmoji>) : List<DiscordEmoji> by items
`equals` and `hashCode` produced by data classes don't conform to the requirements of `List`, I suggest to simply not implement `List`.

2025-04-26 16:53 UTC, lukellmann commented on core/src/commonMain/kotlin/entity/Emoji.kt
> +    public suspend fun delete(reason: String?) {
This is a binary incompatible change, please keep the default argument.

2025-04-26 16:53 UTC, lukellmann commented on core/src/commonMain/kotlin/Kord.kt
> +    }
`emit` is missing, this flow will always be empty.

2025-04-26 16:53 UTC, lukellmann commented on core/src/commonMain/kotlin/entity/Emoji.kt
> + * Superclass for all non standard emojis.
The comment on `Emoji` should be updated to say what the subtypes are.

2025-04-26 16:53 UTC, lukellmann commented on core/src/commonMain/kotlin/entity/Emoji.kt
> +public sealed class CustomEmoji : Emoji, KordEntity, Strategizable {
sealed interface would be nicer

2025-04-26 16:53 UTC, lukellmann commented on core/src/commonMain/kotlin/entity/Emoji.kt
> +public sealed class CustomEmoji : Emoji, KordEntity, Strategizable {
Should abstract override `withStrategy` to return `CustomEmoji`.

2025-04-26 16:53 UTC, lukellmann commented on rest/src/commonMain/kotlin/route/Route.kt
> +        Unit.serializer()
Please use `NoStrategy` instead.

2025-04-26 16:53 UTC, lukellmann commented on rest/src/commonMain/kotlin/route/Route.kt
> +        "/applications/$ApplicationId/emojis/",
Please remove trailing /

2025-04-26 16:53 UTC, lukellmann commented on rest/src/commonMain/kotlin/service/ApplicationService.kt
> +    public suspend inline fun modifyApplicationEmoji(
Please remove `inline`.

2025-04-26 16:53 UTC, lukellmann commented on rest/src/commonMain/kotlin/service/ApplicationService.kt
> +    public suspend inline fun deleteApplicationEmoji(
Please remove `inline`.

2025-04-26 16:55 UTC, lukellmann commented on common/src/commonMain/kotlin/entity/DiscordEmoji.kt
> +public data class ApplicationEmojis(val items: List<DiscordEmoji>) : List<DiscordEmoji> by items
Or better remove this class as a whole.

2025-04-26 16:58 UTC, lukellmann commented on common/src/commonMain/kotlin/entity/DiscordEmoji.kt
> +public data class ApplicationEmojis(val items: List<DiscordEmoji>) : List<DiscordEmoji> by items
Nope, don't remove, discord returns a JSON object with `items` in it.

2025-04-26 17:16 UTC, DRSchlaubi commented on common/src/commonMain/kotlin/entity/DiscordEmoji.kt
> +public data class ApplicationEmojis(val items: List<DiscordEmoji>) : List<DiscordEmoji> by items
We could just make it a value class instead of a data class

2025-04-26 17:18 UTC, DRSchlaubi commented on core/src/commonMain/kotlin/entity/Emoji.kt
> + * Superclass for all non standard emojis.
It's already mentioned using @see, so why mention it twice

2025-04-26 17:19 UTC, lukellmann commented on common/src/commonMain/kotlin/entity/DiscordEmoji.kt
> +public data class ApplicationEmojis(val items: List<DiscordEmoji>) : List<DiscordEmoji> by items
that doesn't fix it either

2025-04-26 17:21 UTC, lukellmann commented on core/src/commonMain/kotlin/entity/Emoji.kt
> + * Superclass for all non standard emojis.
I was referring to this line: https://github.com/kordlib/kord/blob/d23b8c5a2658ddde7e4e367d5ac8397f62ac1928/core/src/commonMain/kotlin/entity/Emoji.kt#L21

2025-04-26 18:31 UTC, lukellmann commented
See https://github.com/kordlib/kord/compare/2002d0c0ec1a0336f589b68a0d2ca2af1ce73177...eaf5dbe1755a4b2005098c6a931465266fed0b65 for a cleaner diff of ABI changes.